# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [33]:
# 1. 
rand_array = np.random.random((2, 3, 1))
print(rand_array)
seven_array = np.full_like(rand_array, 6)
print(seven_array)
one_array = np.ones_like(seven_array)
print(one_array)

# 2. 
print(rand_array[1, 1])
print(seven_array[0, 0])
print(one_array[1, 2])

print(rand_array[1])
print(seven_array[0])
print(one_array[1])

print(rand_array[1, 0:2])
print(seven_array[0, 0:2])
print(one_array[1, 1:3])

# 3. The x: syntax will take the remaining parts of the current dimension,
# while ... takes the remaining parts of all remaining dimensions
print("test 1", rand_array[0:])
print("test 2", rand_array[0, ...])

[[[0.6723796 ]
  [0.94624591]
  [0.90529135]]

 [[0.47726334]
  [0.72827781]
  [0.06692691]]]
[[[6.]
  [6.]
  [6.]]

 [[6.]
  [6.]
  [6.]]]
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
[0.72827781]
[6.]
[1.]
[[0.47726334]
 [0.72827781]
 [0.06692691]]
[[6.]
 [6.]
 [6.]]
[[1.]
 [1.]
 [1.]]
[[0.47726334]
 [0.72827781]]
[[6.]
 [6.]]
[[1.]
 [1.]]
test 1 [[[0.6723796 ]
  [0.94624591]
  [0.90529135]]

 [[0.47726334]
  [0.72827781]
  [0.06692691]]]
test 2 [[0.6723796 ]
 [0.94624591]
 [0.90529135]]


## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [45]:
print(rand_array < 0.5)
print(rand_array[rand_array < 0.5])

print(rand_array > 0.5)
print(rand_array[rand_array > 0.5])

print(rand_array == 0.9)
print(rand_array[rand_array == 0.9])

print(rand_array[(rand_array > 0.2) & (rand_array < 0.5)])
print(rand_array[(rand_array > 0.2) | (rand_array < 0.1)])

[[[False]
  [False]
  [False]]

 [[ True]
  [False]
  [ True]]]
[0.47726334 0.06692691]
[[[ True]
  [ True]
  [ True]]

 [[False]
  [ True]
  [False]]]
[0.6723796  0.94624591 0.90529135 0.72827781]
[[[False]
  [False]
  [False]]

 [[False]
  [False]
  [False]]]
[]
[0.47726334]
[0.6723796  0.94624591 0.90529135 0.47726334 0.72827781 0.06692691]


## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [46]:
help(np.reshape)
help(np.resize)

# The documentation generally makes sense,
# at least enough for me to get the general
# idea of what it's describing. I'm not sure
# I could grasp even most functions I've encountered
# just by reading the doc yet. It has a very 
# jargon-y feel. I felt this way with R documentation
# for several years and sometimes still do.

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [52]:
print(rand_array)
print(rand_array.T)
print(rand_array.T.shape)

[[[0.6723796 ]
  [0.94624591]
  [0.90529135]]

 [[0.47726334]
  [0.72827781]
  [0.06692691]]]
[[[0.6723796  0.47726334]
  [0.94624591 0.72827781]
  [0.90529135 0.06692691]]]
(1, 3, 2)


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [76]:
nines = np.array([[9, 9, 9], [9, 9, 9], [9, 9, 9]])
print("original array \n", nines)
print("shape \n", nines.shape)

np.resize(nines, (3, 5))

fours = np.full_like(a= nines, fill_value = 4)
print("original array \n", fours)
np.resize(fours, (4, 3))

hello = np.full((8, 2), "hi")
print("original array \n", hello)
np.reshape(hello, (4, 4))

original array 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
shape 
 (3, 3)
original array 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]
original array 
 [['hi' 'hi']
 ['hi' 'hi']
 ['hi' 'hi']
 ['hi' 'hi']
 ['hi' 'hi']
 ['hi' 'hi']
 ['hi' 'hi']
 ['hi' 'hi']]


array([['hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi']], dtype='<U2')

## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [125]:
threeD_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(threeD_array)
print(threeD_array.shape)

np.array([[[0, 0]], [[0, 0]]]).shape

# Append row:
threeD_array_update = np.append(threeD_array, np.array([[[0, 0]], [[0, 0]]]), axis = 1)
# Why can't we just feed it a single row and have it append that?

print(threeD_array_update)

# Append col:
print(np.append(threeD_array_update, np.array([[[0], [0], [0]], [[0], [0], [0]]]), axis = 2))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [3 4]
  [0 0]]

 [[5 6]
  [7 8]
  [0 0]]]
[[[1 2 0]
  [3 4 0]
  [0 0 0]]

 [[5 6 0]
  [7 8 0]
  [0 0 0]]]


## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [128]:
help(np.insert)
help(np.delete)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [150]:
print("original \n", np.ones((3, 2, 2)))

ones_edit = np.insert(arr = np.ones((3, 2, 2)), obj = 2, values = 3, axis = 1)
print(ones_edit)
ones_edit = np.delete(arr = ones_edit, obj = 1, axis = 2)
print(ones_edit)

original 
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[1. 1.]
  [1. 1.]
  [3. 3.]]

 [[1. 1.]
  [1. 1.]
  [3. 3.]]

 [[1. 1.]
  [1. 1.]
  [3. 3.]]]
[[[1.]
  [1.]
  [3.]]

 [[1.]
  [1.]
  [3.]]

 [[1.]
  [1.]
  [3.]]]


## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [151]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


**Concatenate**: The two arrays are joined together along a shared dimension (here horizontally).
**vstack**: Combines two arrays by making them rows within a single dimension.
**hstack**: Combines two arrays by joining them along the shared horizontal dimension, but retaining their vertical dimension.
**column_stack**: Combines two arrays like hstack unless they're one dimensional, in which case they will be made into a single two dimensional array.

## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [ ]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

**hsplit**: Retains the structure (i.e., 2D) overall, but breaks into two sub-arrays at a point along the horizontal axis.
**vsplit**: Does not retain the structure, splitting at a point in the vertical axis into two arrays with one less dimension.