# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
# Import numpy
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [9]:
one_d_array = np.array(["one", "two", "three"])
two_d_array = np.array([["one", "two", "three"], ["a", "b", "c"]])
# Note to self: np doesn't seem to like when the sub lists aren't the same lengths
three_d_array = np.array([[["one", "two", "three"], ["a", "b", "c"]], [["uno", "dos", "tres"], ["catorce", "catorce", "catorce"]]])

print(one_d_array)
print(two_d_array)
print(my_3d_array)

['one' 'two' 'three']
[['one' 'two' 'three']
 ['a' 'b' 'c']]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [14]:
# Here's a super cool array
cool_array = np.array([["this", "is", "a", "ray"], ["it", "is", "soup", "cool"]])

# Number of dimensions
print("ndim", cool_array.ndim)
# Shape of the array / its dimensions
print("shape", cool_array.shape)
# Number of elements in the array
print("size", cool_array.size)
# Type of data in the array
print("dtype", cool_array.dtype)
# Length of an array element in bytes
print("itemsize", cool_array.itemsize)
# The object pointing to the array's data
print("data", cool_array.data)
# Total bytes the array's elements take up
print("nbytes", cool_array.nbytes)

ndim 2
shape (2, 4)
size 8
dtype <U4
itemsize 16
data <memory at 0x000002841A98EF28>
nbytes 128


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [19]:
# Create an array of ones with 2 rows and 3 cols
one_array = np.ones((2, 3))
print(one_array)

# Create an array of zeroes with 2 rows and 3 cols
zero_array = np.zeros((2, 3))
print(zero_array)

# Create an empty one-dimensional array
empty_array = np.empty(5)
print(empty_array)

# Create a 1 x 1 array of text
text_array = np.full((1, 1), "test")
print(text_array)

# Create an array of data from 0 to 100 by 10
hundo_array = np.arange(0, 100, 10)
print(hundo_array)

# Create an array of evenly spaced numbers from 0 to 100
space_array = np.linspace(0, 100, 7)
print(space_array)

# Create an array of random floats from 0 to 1.0
rando_array = np.random.random((15, ))
print(rando_array)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[2.12199579e-313 6.36598737e-313 1.06099790e-312 1.48539705e-312
 1.90979621e-312]
[['test']]
[ 0 10 20 30 40 50 60 70 80 90]
[  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.        ]
[0.49441128 0.23892289 0.16083416 0.99538444 0.01914808 0.14457233
 0.17912772 0.84137897 0.51714643 0.95901591 0.13800283 0.5379449
 0.75216772 0.521324   0.94063466]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [42]:
good_array_1 = np.random.random((2, 2))
print(good_array_1)
good_array_2 = np.ones((5, 2, 2))
print(good_array_2)

good_array_1 + good_array_2
good_array_1 - good_array_2
good_array_1 * good_array_2

bad_array_1 = np.random.random((2, 2))
print(bad_array_1)
bad_array_2 = np.ones((5, 2, 4))
print(bad_array_2)

bad_array_1 + bad_array_2

[[0.9705928  0.80329711]
 [0.22946904 0.44469091]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[0.68553149 0.73201019]
 [0.6066331  0.3237968 ]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


ValueError: operands could not be broadcast together with shapes (2,2) (5,2,4) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [73]:
array_1 = np.ones(8)
print(array_1)
array_2 = np.random.random(4)
print(array_2)
array_3 = np.array([[1, 5, 7], [3, 6, 1]])
print(array_3)

# Sum the full array
np.sum(array_1)

# Find minimums at each array index
print(np.minimum(array_3[0], array_3[1]))

# Find cumulative sum
print(np.cumsum(array_1))
print(np.cumsum(array_3))

# Find mean of array
print(np.mean(array_3))

# Find pearson correlations between arrays
print(np.corrcoef(array_3))

# Find standard deviation
print(np.std(array_2))

# Find the variance of the array
print(np.var(array_1))

[1. 1. 1. 1. 1. 1. 1. 1.]
[0.67129795 0.87818157 0.09015393 0.72084302]
[[1 5 7]
 [3 6 1]]
[1 5 1]
[1. 2. 3. 4. 5. 6. 7. 8.]
[ 1  6 13 16 22 23]
3.8333333333333335
[[ 1.         -0.21677749]
 [-0.21677749  1.        ]]
0.29858998072235865
0.0


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [77]:
is_it_true_1 = [False, False, True]
is_it_true_2 = [False, True, True]

# Check if both are true
print(np.logical_and(is_it_true_1, is_it_true_2))
# Check if one is true
print(np.logical_or(is_it_true_1, is_it_true_2))
# Compute inverse of logical array
print(np.logical_not(is_it_true_1))

[False False  True]
[False  True  True]
[ True  True False]
